/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TameOfThrones;

import java.util.List;
import java.io.IOException;
import java.io.File;
import java.io.InputStream;
import java.io.FileInputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;

import TameOfThrones.excahnges.GetFileResponse;
import TameOfThrones.models.Kingdom;
import TameOfThrones.models.Universe;
import TameOfThrones.utils.Helper;

public class GeekTrust {
    public static void main(String[] args) throws IOException{

        // TO RUN THE MAIN METHOD PROVIDE THE PATH OF THE INPUT FILE AS COMMAND LINE ARG AS
        // ./gradlew run --args='path/to/the/input/file'

        if (args.length == 0) {
            System.out.println("Please provide the path of the input file.");
            System.exit(0);
        }
        
        final String GOOD_RESPONSE = "GOOD";
        final String BAD_RESPONSE = "BAD";

        GetFileResponse fileResponse = Helper.resolveFileFromResources(args[0]);

        if (fileResponse.getResponse().equals(BAD_RESPONSE)) {
            System.out.println(fileResponse.getMessage());
            System.exit(0);
        } 

        String fileContent = fileResponse.getFileContent();
        
        List<Kingdom> kingdoms = Helper.parseKingdoms(fileContent);

        
        // CREATING AN UNIVERSE WITH ITS KINGDOMS
        Universe southeros = new Universe(kingdoms);

        Kingdom ruler = southeros.getRuler();

        if (ruler != null) {
            // THERE IS A RUER
            String rulerName = ruler.getKingdomName();
            String supportersOfRuler = ruler.getAllSupporterNamesAsString();
            System.out.println(rulerName + " " + supportersOfRuler);
        } else {
            // THERE IS NO RULER
            System.out.println("NONE");
        }
        
    }

}
